### ISSUE TITLE
Developing PoseidonML with venv modules

### ISSUE THREAD

**Issue by scottkelso** [CyberReboot/PoseidonML#122]
Hi there,

I am struggling to understand what way I can develop this project with the `poseidonml` package being installed in venv.  Surely this means that the changes I make locally cannot be applied.

I am currently adding files into the local PoseidonML directory, but am getting import errors like the one below because venv doesn't run a local instance

```
Traceback (most recent call last):
 File "train_NewModel.py", line 9, in <module>
   from poseidonml.NewModel import NewModel
ImportError: No module named poseidonml.NewModel
```

I can manually edit files in `~/workspace/PoseidonML/venv/local/lib/python2.7/site-packages/poseidonml` to see my imports work, but these changes are not included in our forked PoseidonML repo, and will be overwritten any time these dependencies are refreshed.

What is the proper procedure for developing? How would you suggest we tackle these imports?

Thanks in advance.

**Comment by cglewis** [comment]
That part of PoseidonML is a package since it's shared in both implementations (OneLayer and RandomForest) and since they're run in Docker containers, the context for building parent directories is lost.  I'd recommend making your changes in the utils directory, and then doing a `pip install .` from the root of the repo, that way your changes will get installed in the package, whether it's a fork or for dev on the main repo.

**Comment by scottkelso** [comment]
Fantastic, that did the trick! Cheers @cglewis

**Comment by scottkelso** [comment]
Sorry @cglewis, I spoke too soon.  The above advice _did_ update the files in the venv folder, but didn't elimate the error when running training using docker.

**Steps Taken**
* added a `SVMModel.py` into utils 
* copied the `DeviceClassifier/OneLayer/` folder and renamed all OneLayer occurrences with SVM so it is now `DeviceClassifier/SVM/`
* updated the import of `train_SVM.py` to use new `SVMModel.py`
(from poseidonml.OneLayer import OneLayerModel >>> from poseidonml.SVMModel import SVMModel)
* ran `pip install .` from root of the project and witness the new `SVMModel.py` appear in the external libraries folders
* run `~/workspace/PoseidonML# docker run -it -v "/tmp/models:/SVM/models" -v "******/workspace/traffic/QuickDataset:/pcaps/" -e SKIP_RABBIT=true poseidonml:svm train_SVM.py`


But `train_SVM.py` still cannot see `poseidonml.SVMModel` even though I have confirmed that it is in the external libraries folders as below.

1) `~/workspace/PoseidonML/venv/local/lib/python2.7/site-packages/poseidonml/SVMModel.py`
2) `~/workspace/PoseidonML/venv/lib/python2.7/site-packages/poseidonml/SVMModel.py`

This the exact error I get when running the last step above (`docker run -it...`)
```
Traceback (most recent call last):
  File "train_SVM.py", line 12, in <module>
    from poseidonml.SVMModel import SVMModel
ImportError: No module named 'poseidonml.SVMModel'

```

I have also tried pushing my changes to our gitlab repo and changing the url in the `setup.py` file to point to it.  Are there any steps I am missing?

I am using PyCharm as my IDE and let PyCharm install the dependencies automatically. (pip, setuptools, tensorflow eta...)

**Comment by cglewis** [comment]
How recently have you pulled from master? I pushed two things this morning that will hopefully fix that, but also require you to something slightly different than what you have above.

The first is I changed the base image install the local utils as the poseidonml library, as opposed to the published on, so that you can use dev changes in the docker container too.

The second is I removed the python file from CMD and put it into ENTRYPOINT - this is for Poseidon's use, which means the Makefile (just updated that) now overrides the ENTRYPOINT to just be python3, so that the python file can be the CMD again.

So for your above example, I recommend doing:
```
make build_onelayer
```
That will build the image with your changes and call it poseidonml:onelayer

Then you can run it with:
```
docker run -it -v "/tmp/models:/SVM/models" -v "******/workspace/traffic/QuickDataset:/pcaps/" -e SKIP_RABBIT=true --entrypoint=python3 poseidonml:svm SVMModel.py
```

But at this point, it sounds like your fork has changed quite a bit from ours, so it's gonna be kinda tricky to troubleshoot.

**Comment by scottkelso** [comment]
Apologies for the slow response. You are correct, I was a day or two behind.  That seems to have eliminated all module related errors!

Now to see if we can get any decent results with SVM! Thanks again.
